package pipelineclient.UI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 11437
 */
import java.awt.Font;
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import pipelineclient.*;
import pipelineclient.utility.*;
import static pipelineclient.Var.*;
import static pipelineclient.utility.Convert.*;

public class ClientFrame extends javax.swing.JFrame {

    Timer timer;
    ClientStep task;
    int MAX_CODELEN = 65536;

    private void setEdit(boolean edit) {
        jTextField_F_PredPC.setEditable(edit);
        jTextField_D_Stat.setEditable(edit);
        jTextField_D_Ifun.setEditable(edit);
        jTextField_D_RA.setEditable(edit);
        jTextField_D_RB.setEditable(edit);
        jTextField_D_Icode.setEditable(edit);
        jTextField_D_ValP.setEditable(edit);
        jTextField_D_ValC.setEditable(edit);
        jTextField_E_Stat.setEditable(edit);
        jTextField_E_Ifun.setEditable(edit);
        jTextField_E_ValC.setEditable(edit);
        jTextField_E_ValA.setEditable(edit);
        jTextField_E_ValB.setEditable(edit);
        jTextField_E_Icode.setEditable(edit);
        jTextField_E_DstM.setEditable(edit);
        jTextField_E_SrcA.setEditable(edit);
        jTextField_E_SrcB.setEditable(edit);
        jTextField_E_DstE.setEditable(edit);
        jTextField_M_Stat.setEditable(edit);
        jTextField_M_ValA.setEditable(edit);
        jTextField_M_ValE.setEditable(edit);
        jTextField_M_CC.setEditable(edit);
        jTextField_M_Icode.setEditable(edit);
        jTextField_M_DstE.setEditable(edit);
        jTextField_M_DstM.setEditable(edit);
        jTextField_M_Cnd.setEditable(edit);
        jTextField_W_Stat.setEditable(edit);
        jTextField_W_Icode.setEditable(edit);
        jTextField_W_ValE.setEditable(edit);
        jTextField_W_ValM.setEditable(edit);
        jTextField_W_DstE.setEditable(edit);
        jTextField_W_DstM.setEditable(edit);
        jTextField_Cycle.setEditable(edit);
        jTextField_eax.setEditable(edit);
        jTextField_ecx.setEditable(edit);
        jTextField_edx.setEditable(edit);
        jTextField_ebx.setEditable(edit);
        jTextField_esp.setEditable(edit);
        jTextField_ebp.setEditable(edit);
        jTextField_esi.setEditable(edit);
        jTextField_edi.setEditable(edit);
        jTextField_D_Instr.setEditable(edit);
        jTextField_E_Instr.setEditable(edit);
        jTextField_M_Instr.setEditable(edit);
        jTextField_W_Instr.setEditable(edit);
    }

    private void setButtonVisable(boolean vis) {
        jButton_Play.setVisible(vis);
        jButton_Stop.setVisible(!vis);
        jButton_NextStep.setVisible(vis);
        jButton_Reset.setVisible(vis);
        jButton_Refresh.setVisible(vis);
        jRadioButton_1HZ.setVisible(vis);
        jRadioButton_5HZ.setVisible(vis);
        jRadioButton_20HZ.setVisible(vis);
    }

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {
        initComponents();
        timer = new Timer();
        task = null;
        Option.setSelected(jRadioButton_1HZ.getModel(), true);

        setEdit(false);
        setButtonVisable(true);

        DefaultTableCellRenderer hr = (DefaultTableCellRenderer) jTable_Code.getTableHeader().getDefaultRenderer();
        hr.setHorizontalAlignment(JLabel.CENTER);
        jTable_Code.getTableHeader().setFont(new Font("Lucida Grande", Font.BOLD, 14));
        jTable_Code.getTableHeader().setDefaultRenderer(hr);
        jTable_Memory.getTableHeader().setFont(new Font("Lucida Grande", Font.BOLD, 14));
        jTable_Memory.getTableHeader().setDefaultRenderer(hr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Option = new javax.swing.ButtonGroup();
        jTabbedPane_Navigation = new javax.swing.JTabbedPane();
        jPanel_FIle = new javax.swing.JPanel();
        jButton_OpenFile = new javax.swing.JButton();
        jPanel_Code = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Code = new javax.swing.JTable();
        jPanel_Process = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton_Play = new javax.swing.JButton();
        jButton_NextStep = new javax.swing.JButton();
        jButton_Reset = new javax.swing.JButton();
        jButton_Refresh = new javax.swing.JButton();
        jLabel_Cycle = new javax.swing.JLabel();
        jTextField_Cycle = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jButton_Stop = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jRadioButton_1HZ = new javax.swing.JRadioButton();
        jRadioButton_5HZ = new javax.swing.JRadioButton();
        jRadioButton_20HZ = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Fetch = new javax.swing.JLabel();
        jLabel_Decode = new javax.swing.JLabel();
        jLabel_Excute = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel_F_PredPC = new javax.swing.JLabel();
        jTextField_F_PredPC = new javax.swing.JTextField();
        jLabel_D_Stat = new javax.swing.JLabel();
        jLabel_D_Icode = new javax.swing.JLabel();
        jLabel_E_Stat = new javax.swing.JLabel();
        jLabel_E_Icode = new javax.swing.JLabel();
        jLabel_M_Stat = new javax.swing.JLabel();
        jLabel_M_Icode = new javax.swing.JLabel();
        jLabel_W_Stat = new javax.swing.JLabel();
        jTextField_D_Stat = new javax.swing.JTextField();
        jTextField_D_Icode = new javax.swing.JTextField();
        jTextField_E_Stat = new javax.swing.JTextField();
        jTextField_E_Icode = new javax.swing.JTextField();
        jTextField_M_Stat = new javax.swing.JTextField();
        jTextField_M_Icode = new javax.swing.JTextField();
        jTextField_W_Stat = new javax.swing.JTextField();
        jLabel_E_Ifun = new javax.swing.JLabel();
        jLabel_E_DstM = new javax.swing.JLabel();
        jTextField_E_Ifun = new javax.swing.JTextField();
        jTextField_E_DstM = new javax.swing.JTextField();
        jLabel_E_ValC = new javax.swing.JLabel();
        jLabel_E_SrcA = new javax.swing.JLabel();
        jTextField_E_ValC = new javax.swing.JTextField();
        jTextField_E_SrcA = new javax.swing.JTextField();
        jLabel_E_ValA = new javax.swing.JLabel();
        jLabel_E_SrcB = new javax.swing.JLabel();
        jTextField_E_ValA = new javax.swing.JTextField();
        jTextField_E_SrcB = new javax.swing.JTextField();
        jLabel_E_ValB = new javax.swing.JLabel();
        jTextField_E_ValB = new javax.swing.JTextField();
        jLabel_E_DstE = new javax.swing.JLabel();
        jTextField_E_DstE = new javax.swing.JTextField();
        jLabel_D_Ifun = new javax.swing.JLabel();
        jLabel_D_ValP = new javax.swing.JLabel();
        jTextField_D_Ifun = new javax.swing.JTextField();
        jTextField_D_ValP = new javax.swing.JTextField();
        jLabel_D_RA = new javax.swing.JLabel();
        jLabel_D_ValC = new javax.swing.JLabel();
        jTextField_D_RA = new javax.swing.JTextField();
        jTextField_D_ValC = new javax.swing.JTextField();
        jLabel_D_RB = new javax.swing.JLabel();
        jTextField_D_RB = new javax.swing.JTextField();
        jLabel_M_ValA = new javax.swing.JLabel();
        jTextField_M_ValA = new javax.swing.JTextField();
        jLabel_M_CC = new javax.swing.JLabel();
        jTextField_M_CC = new javax.swing.JTextField();
        jLabel_M_DstM = new javax.swing.JLabel();
        jTextField_M_DstM = new javax.swing.JTextField();
        jLabel_M_ValE = new javax.swing.JLabel();
        jTextField_M_ValE = new javax.swing.JTextField();
        jLabel_M_DstE = new javax.swing.JLabel();
        jTextField_M_DstE = new javax.swing.JTextField();
        jLabel_W_Icode = new javax.swing.JLabel();
        jTextField_W_Icode = new javax.swing.JTextField();
        jLabel_W_ValE = new javax.swing.JLabel();
        jTextField_W_ValE = new javax.swing.JTextField();
        jLabel_W_ValM = new javax.swing.JLabel();
        jTextField_W_ValM = new javax.swing.JTextField();
        jLabel_W_DstE = new javax.swing.JLabel();
        jTextField_W_DstE = new javax.swing.JTextField();
        jLabel_W_DstM = new javax.swing.JLabel();
        jTextField_W_DstM = new javax.swing.JTextField();
        jLabel_Memory = new javax.swing.JLabel();
        jLabel_Writeback = new javax.swing.JLabel();
        jLabel_M_Cnd = new javax.swing.JLabel();
        jTextField_M_Cnd = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel_eax = new javax.swing.JLabel();
        jLabel_ecx = new javax.swing.JLabel();
        jLabel_edx = new javax.swing.JLabel();
        jLabel_ebx = new javax.swing.JLabel();
        jLabel_esp = new javax.swing.JLabel();
        jLabel_ebp = new javax.swing.JLabel();
        jLabel_esi = new javax.swing.JLabel();
        jLabel_edi = new javax.swing.JLabel();
        jTextField_eax = new javax.swing.JTextField();
        jTextField_ecx = new javax.swing.JTextField();
        jTextField_edx = new javax.swing.JTextField();
        jTextField_ebx = new javax.swing.JTextField();
        jTextField_esp = new javax.swing.JTextField();
        jTextField_ebp = new javax.swing.JTextField();
        jTextField_esi = new javax.swing.JTextField();
        jTextField_edi = new javax.swing.JTextField();
        jLabel_Register = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel_M_Instr = new javax.swing.JLabel();
        jTextField_E_Instr = new javax.swing.JTextField();
        jLabel_Instruction = new javax.swing.JLabel();
        jTextField_W_Instr = new javax.swing.JTextField();
        jLabel_E_Instr = new javax.swing.JLabel();
        jLabel_D_Instr = new javax.swing.JLabel();
        jTextField_D_Instr = new javax.swing.JTextField();
        jTextField_M_Instr = new javax.swing.JTextField();
        jLabel_W_Instr = new javax.swing.JLabel();
        jPanel_Memory = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Memory = new javax.swing.JTable();
        jPanel_About = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_Pipeline = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane_Navigation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane_NavigationMouseClicked(evt);
            }
        });

        jButton_OpenFile.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        jButton_OpenFile.setText("Open File");
        jButton_OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OpenFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_FIleLayout = new javax.swing.GroupLayout(jPanel_FIle);
        jPanel_FIle.setLayout(jPanel_FIleLayout);
        jPanel_FIleLayout.setHorizontalGroup(
            jPanel_FIleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FIleLayout.createSequentialGroup()
                .addGap(536, 536, 536)
                .addComponent(jButton_OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(545, Short.MAX_VALUE))
        );
        jPanel_FIleLayout.setVerticalGroup(
            jPanel_FIleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FIleLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jButton_OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jTabbedPane_Navigation.addTab("File", jPanel_FIle);

        jTable_Code.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable_Code.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Address", "Binary Code", "Instruction"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Code);
        if (jTable_Code.getColumnModel().getColumnCount() > 0) {
            jTable_Code.getColumnModel().getColumn(0).setResizable(false);
            jTable_Code.getColumnModel().getColumn(1).setResizable(false);
            jTable_Code.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel_CodeLayout = new javax.swing.GroupLayout(jPanel_Code);
        jPanel_Code.setLayout(jPanel_CodeLayout);
        jPanel_CodeLayout.setHorizontalGroup(
            jPanel_CodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_CodeLayout.setVerticalGroup(
            jPanel_CodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane_Navigation.addTab("Code", jPanel_Code);

        jButton_Play.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jButton_Play.setText("Play");
        jButton_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PlayActionPerformed(evt);
            }
        });

        jButton_NextStep.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jButton_NextStep.setText("Next");
        jButton_NextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextStepActionPerformed(evt);
            }
        });

        jButton_Reset.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jButton_Reset.setText("Reset");
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        jButton_Refresh.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jButton_Refresh.setText("Refresh");
        jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshActionPerformed(evt);
            }
        });

        jLabel_Cycle.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel_Cycle.setText("Cycle");

        jTextField_Cycle.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextField_Cycle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Cycle.setText("0");
        jTextField_Cycle.setToolTipText("");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton_Stop.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jButton_Stop.setText("Stop");
        jButton_Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StopActionPerformed(evt);
            }
        });

        Option.add(jRadioButton_1HZ);
        jRadioButton_1HZ.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jRadioButton_1HZ.setText("1HZ");

        Option.add(jRadioButton_5HZ);
        jRadioButton_5HZ.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jRadioButton_5HZ.setText("5HZ");

        Option.add(jRadioButton_20HZ);
        jRadioButton_20HZ.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jRadioButton_20HZ.setText("20HZ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_1HZ)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton_NextStep, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton_Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton_Play, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_Cycle, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_Cycle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton_20HZ)
                            .addComponent(jRadioButton_5HZ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Cycle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Cycle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton_Play)
                        .addGap(0, 0, 0)
                        .addComponent(jButton_Stop)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_NextStep)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Reset)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Refresh)
                        .addGap(54, 54, 54)
                        .addComponent(jRadioButton_1HZ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_5HZ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_20HZ)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(149, 149, 149))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_NextStep, jButton_Play, jButton_Refresh, jButton_Reset, jButton_Stop});

        jLabel_Fetch.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel_Fetch.setText("Fetch");

        jLabel_Decode.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel_Decode.setText("Decode");

        jLabel_Excute.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel_Excute.setText("Excute");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_F_PredPC.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_F_PredPC.setText("F_PredPC");

        jTextField_F_PredPC.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jTextField_F_PredPC.setToolTipText("");

        jLabel_D_Stat.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_D_Stat.setText("D_Stat");

        jLabel_D_Icode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_D_Icode.setText("D_Icode");

        jLabel_E_Stat.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_Stat.setText("E_Stat");

        jLabel_E_Icode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_Icode.setText("E_Icode");

        jLabel_M_Stat.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_M_Stat.setText("M_Stat");

        jLabel_M_Icode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_M_Icode.setText("M_Icode");
        jLabel_M_Icode.setToolTipText("");

        jLabel_W_Stat.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_W_Stat.setText("W_Stat");

        jTextField_D_Stat.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_D_Icode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_E_Stat.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_E_Icode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_M_Stat.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_M_Icode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_W_Stat.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_E_Ifun.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_Ifun.setText("E_Ifun");
        jLabel_E_Ifun.setToolTipText("");

        jLabel_E_DstM.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_DstM.setText("E_DstM");

        jTextField_E_Ifun.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_E_DstM.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_E_ValC.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_ValC.setText("E_ValC");

        jLabel_E_SrcA.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_SrcA.setText("E_SrcA");

        jTextField_E_ValC.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_E_SrcA.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_E_ValA.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_ValA.setText("E_ValA");

        jLabel_E_SrcB.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_SrcB.setText("E_SrcB");

        jTextField_E_ValA.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_E_SrcB.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_E_ValB.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_ValB.setText("E_ValB");

        jTextField_E_ValB.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_E_DstE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_DstE.setText("E_DstE");

        jTextField_E_DstE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_D_Ifun.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_D_Ifun.setText("D_Ifun");

        jLabel_D_ValP.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_D_ValP.setText("D_ValP");
        jLabel_D_ValP.setToolTipText("");

        jTextField_D_Ifun.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_D_ValP.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_D_RA.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_D_RA.setText("D_RA");

        jLabel_D_ValC.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_D_ValC.setText("D_ValC");

        jTextField_D_RA.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jTextField_D_ValC.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_D_RB.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_D_RB.setText("D_RB");

        jTextField_D_RB.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_M_ValA.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_M_ValA.setText("M_ValA");

        jTextField_M_ValA.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_M_CC.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_M_CC.setText("M_CC");

        jTextField_M_CC.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_M_DstM.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_M_DstM.setText("M_DstM");

        jTextField_M_DstM.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_M_ValE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_M_ValE.setText("M_ValE");

        jTextField_M_ValE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_M_DstE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_M_DstE.setText("M_DstE");

        jTextField_M_DstE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_W_Icode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_W_Icode.setText("W_Icode");

        jTextField_W_Icode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_W_ValE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_W_ValE.setText("W_ValE");

        jTextField_W_ValE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_W_ValM.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_W_ValM.setText("W_ValM");

        jTextField_W_ValM.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_W_DstE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_W_DstE.setText("W_DstE");

        jTextField_W_DstE.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_W_DstM.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_W_DstM.setText("W_DstM");

        jTextField_W_DstM.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel_Memory.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel_Memory.setText("Memory");

        jLabel_Writeback.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        jLabel_Writeback.setText("Writeback");

        jLabel_M_Cnd.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_M_Cnd.setText("M_Cnd");

        jTextField_M_Cnd.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Writeback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel_Memory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Excute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Decode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Fetch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_F_PredPC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_F_PredPC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_D_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_D_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_D_Ifun, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_D_Ifun, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_D_RA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_D_RA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_D_RB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_D_RB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_D_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_D_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_D_ValP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_D_ValP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_D_ValC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_D_ValC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_E_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_E_DstM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_DstM, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_E_SrcA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_SrcA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_E_SrcB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_SrcB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_E_DstE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_DstE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_M_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_M_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_M_ValA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_M_ValA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_M_ValE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_M_ValE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_M_CC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_M_CC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_M_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_M_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_M_DstE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_M_DstE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_M_DstM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_M_DstM, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_M_Cnd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_M_Cnd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_W_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_W_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_W_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_W_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_W_ValE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_W_ValE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_E_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_E_Ifun, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_Ifun, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_E_ValC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_ValC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_E_ValA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_ValA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_E_ValB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_E_ValB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_W_ValM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_W_ValM, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_W_DstE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_W_DstE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_W_DstM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_W_DstM, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel_Fetch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel_Decode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel_Excute, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel_Memory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel_Writeback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_F_PredPC)
                    .addComponent(jTextField_F_PredPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_D_Stat)
                    .addComponent(jTextField_D_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_D_Ifun)
                    .addComponent(jTextField_D_Ifun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_D_RA)
                    .addComponent(jTextField_D_RA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_D_RB)
                    .addComponent(jTextField_D_RB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_D_Icode)
                    .addComponent(jTextField_D_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_D_ValP)
                    .addComponent(jTextField_D_ValP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_D_ValC)
                    .addComponent(jTextField_D_ValC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_E_Stat)
                    .addComponent(jTextField_E_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_E_Ifun)
                    .addComponent(jTextField_E_Ifun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_E_ValC)
                    .addComponent(jTextField_E_ValC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_E_ValA)
                    .addComponent(jTextField_E_ValA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_E_ValB)
                    .addComponent(jTextField_E_ValB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_E_Icode)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_E_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_E_DstM)
                        .addComponent(jTextField_E_DstM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_E_SrcA)
                        .addComponent(jTextField_E_SrcA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_E_SrcB)
                        .addComponent(jTextField_E_SrcB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_E_DstE)
                        .addComponent(jTextField_E_DstE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_M_Stat)
                    .addComponent(jTextField_M_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_M_CC)
                    .addComponent(jTextField_M_CC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_M_ValE)
                    .addComponent(jTextField_M_ValE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_M_ValA)
                    .addComponent(jTextField_M_ValA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_M_Icode)
                    .addComponent(jTextField_M_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_M_DstM)
                    .addComponent(jTextField_M_DstM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_M_DstE)
                    .addComponent(jTextField_M_DstE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_M_Cnd)
                    .addComponent(jTextField_M_Cnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_W_Stat)
                    .addComponent(jTextField_W_Stat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_W_Icode)
                    .addComponent(jTextField_W_Icode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_W_ValE)
                    .addComponent(jTextField_W_ValE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_W_ValM)
                    .addComponent(jTextField_W_ValM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_W_DstE)
                    .addComponent(jTextField_W_DstE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_W_DstM)
                    .addComponent(jTextField_W_DstM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_F_PredPC.getAccessibleContext().setAccessibleName("");
        jLabel_D_Stat.getAccessibleContext().setAccessibleName("");
        jLabel_D_Icode.getAccessibleContext().setAccessibleName("");
        jLabel_E_Stat.getAccessibleContext().setAccessibleName("");
        jLabel_E_Icode.getAccessibleContext().setAccessibleName("");
        jLabel_M_Stat.getAccessibleContext().setAccessibleName("");
        jLabel_M_Icode.getAccessibleContext().setAccessibleName("");
        jLabel_W_Stat.getAccessibleContext().setAccessibleName("");
        jLabel_E_Ifun.getAccessibleContext().setAccessibleName("");
        jLabel_E_DstM.getAccessibleContext().setAccessibleName("");
        jLabel_E_ValC.getAccessibleContext().setAccessibleName("");
        jLabel_E_SrcA.getAccessibleContext().setAccessibleName("");
        jLabel_E_ValA.getAccessibleContext().setAccessibleName("");
        jLabel_E_SrcB.getAccessibleContext().setAccessibleName("");
        jLabel_E_ValB.getAccessibleContext().setAccessibleName("");
        jLabel_E_DstE.getAccessibleContext().setAccessibleName("");
        jLabel_D_Ifun.getAccessibleContext().setAccessibleName("");
        jLabel_D_ValP.getAccessibleContext().setAccessibleName("");
        jLabel_D_RA.getAccessibleContext().setAccessibleName("");
        jLabel_D_ValC.getAccessibleContext().setAccessibleName("");
        jLabel_D_RB.getAccessibleContext().setAccessibleName("");
        jLabel_M_ValA.getAccessibleContext().setAccessibleName("");
        jLabel_M_CC.getAccessibleContext().setAccessibleName("");
        jLabel_M_DstM.getAccessibleContext().setAccessibleName("");
        jLabel_M_ValE.getAccessibleContext().setAccessibleName("");
        jLabel_M_DstE.getAccessibleContext().setAccessibleName("");
        jLabel_W_Icode.getAccessibleContext().setAccessibleName("");
        jLabel_W_ValE.getAccessibleContext().setAccessibleName("");
        jLabel_W_ValM.getAccessibleContext().setAccessibleName("");
        jLabel_W_DstE.getAccessibleContext().setAccessibleName("");
        jLabel_W_DstM.getAccessibleContext().setAccessibleName("");

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_eax.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel_eax.setText("eax");

        jLabel_ecx.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel_ecx.setText("ecx");

        jLabel_edx.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel_edx.setText("edx");

        jLabel_ebx.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel_ebx.setText("ebx");

        jLabel_esp.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel_esp.setText("esp");

        jLabel_ebp.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel_ebp.setText("ebp");
        jLabel_ebp.setToolTipText("");

        jLabel_esi.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel_esi.setText("esi");

        jLabel_edi.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel_edi.setText("edi");
        jLabel_edi.setToolTipText("");

        jTextField_edx.setToolTipText("");

        jLabel_Register.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Register.setText("Register");
        jLabel_Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_Register, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_eax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ecx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_edx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ebx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_esp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ebp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_esi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_edi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ecx, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_eax, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_edx, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ebx, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_esp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ebp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_esi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_edi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_eax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_eax))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ecx)
                    .addComponent(jTextField_ecx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_edx)
                    .addComponent(jTextField_edx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ebx)
                    .addComponent(jTextField_ebx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_esp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_esp))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ebp)
                    .addComponent(jTextField_ebp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_esi)
                    .addComponent(jTextField_esi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_edi)
                    .addComponent(jTextField_edi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_eax.getAccessibleContext().setAccessibleName("");
        jLabel_ecx.getAccessibleContext().setAccessibleName("");
        jLabel_edx.getAccessibleContext().setAccessibleName("");
        jLabel_ebx.getAccessibleContext().setAccessibleName("");
        jLabel_esp.getAccessibleContext().setAccessibleName("");
        jLabel_ebp.getAccessibleContext().setAccessibleName("");
        jLabel_esi.getAccessibleContext().setAccessibleName("");
        jLabel_edi.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_M_Instr.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_M_Instr.setText("M");

        jLabel_Instruction.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel_Instruction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Instruction.setText("Instruction");
        jLabel_Instruction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_E_Instr.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_E_Instr.setText("E");

        jLabel_D_Instr.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_D_Instr.setText("D");

        jLabel_W_Instr.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel_W_Instr.setText("W");

        javax.swing.GroupLayout jPanel_ProcessLayout = new javax.swing.GroupLayout(jPanel_Process);
        jPanel_Process.setLayout(jPanel_ProcessLayout);
        jPanel_ProcessLayout.setHorizontalGroup(
            jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator8)
                    .addGroup(jPanel_ProcessLayout.createSequentialGroup()
                        .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ProcessLayout.createSequentialGroup()
                                .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_D_Instr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_E_Instr)
                                    .addComponent(jLabel_M_Instr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_W_Instr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_D_Instr)
                                    .addComponent(jTextField_E_Instr, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_M_Instr)
                                    .addComponent(jTextField_W_Instr)))
                            .addComponent(jLabel_Instruction, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel_ProcessLayout.setVerticalGroup(
            jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_ProcessLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ProcessLayout.createSequentialGroup()
                                .addGap(0, 27, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_ProcessLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel_Instruction, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_D_Instr)
                                    .addComponent(jTextField_D_Instr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_E_Instr)
                                    .addComponent(jTextField_E_Instr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_M_Instr)
                                    .addComponent(jTextField_M_Instr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_ProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_W_Instr)
                                    .addComponent(jTextField_W_Instr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel_M_Instr.getAccessibleContext().setAccessibleName("");
        jLabel_E_Instr.getAccessibleContext().setAccessibleName("");
        jLabel_D_Instr.getAccessibleContext().setAccessibleName("");
        jLabel_W_Instr.getAccessibleContext().setAccessibleName("");

        jTabbedPane_Navigation.addTab("Process", jPanel_Process);

        jTable_Memory.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable_Memory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Address", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_Memory);
        if (jTable_Memory.getColumnModel().getColumnCount() > 0) {
            jTable_Memory.getColumnModel().getColumn(0).setResizable(false);
            jTable_Memory.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel_MemoryLayout = new javax.swing.GroupLayout(jPanel_Memory);
        jPanel_Memory.setLayout(jPanel_MemoryLayout);
        jPanel_MemoryLayout.setHorizontalGroup(
            jPanel_MemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MemoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_MemoryLayout.setVerticalGroup(
            jPanel_MemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MemoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane_Navigation.addTab("Memory", jPanel_Memory);

        jLabel_Pipeline.setFont(new java.awt.Font("微软雅黑", 1, 48)); // NOI18N
        jLabel_Pipeline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Pipeline.setText("Pipeline Simulator");
        jLabel_Pipeline.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Pipeline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Pipeline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("——Lin Shihan & Zhao Wuxu");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_AboutLayout = new javax.swing.GroupLayout(jPanel_About);
        jPanel_About.setLayout(jPanel_AboutLayout);
        jPanel_AboutLayout.setHorizontalGroup(
            jPanel_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AboutLayout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_AboutLayout.setVerticalGroup(
            jPanel_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AboutLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_Navigation.addTab("About", jPanel_About);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Navigation)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Navigation)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Display() {
        String str = PipelineClient.Receive();
        System.out.println(str);
        if (str.length() <= 0) {
            return;
        }
        Map<String, String> Json = JsonUtil.jsonStringToMap(str);
        if (Json.get("status").equals("HALT")) {
            if (task != null) {
                task.cancel();
            }
            JOptionPane.showMessageDialog(null, "Finished!");
            return;
        }

        jTextField_F_PredPC.setText(Json.get("F_predPC"));

        jTextField_D_Stat.setText(Json.get("D_stat"));
        jTextField_D_Ifun.setText(Json.get("D_ifun"));
        jTextField_D_RA.setText(Json.get("D_rA"));
        jTextField_D_RB.setText(Json.get("D_rB"));
        jTextField_D_Icode.setText(Json.get("D_icode"));
        jTextField_D_ValP.setText(Json.get("D_valP"));
        jTextField_D_ValC.setText(Json.get("D_valC"));

        jTextField_E_Stat.setText(Json.get("E_stat"));
        jTextField_E_Ifun.setText(Json.get("E_ifun"));
        jTextField_E_ValC.setText(Json.get("E_valC"));
        jTextField_E_ValA.setText(Json.get("E_valA"));
        jTextField_E_ValB.setText(Json.get("E_valB"));
        jTextField_E_Icode.setText(Json.get("E_icode"));
        jTextField_E_DstM.setText(Json.get("E_dstM"));
        jTextField_E_SrcA.setText(Json.get("E_srcA"));
        jTextField_E_SrcB.setText(Json.get("E_srcB"));
        jTextField_E_DstE.setText(Json.get("E_dstE"));

        jTextField_M_Stat.setText(Json.get("M_stat"));
        jTextField_M_Cnd.setText(Json.get("M_Cnd"));
        jTextField_M_CC.setText(Json.get("zf") + " " + Json.get("sf") + " " + Json.get("of"));
        jTextField_M_ValE.setText(Json.get("M_valE"));
        jTextField_M_Icode.setText(Json.get("M_icode"));
        jTextField_M_ValA.setText(Json.get("M_valA"));
        jTextField_M_DstM.setText(Json.get("M_dstM"));
        jTextField_M_DstE.setText(Json.get("M_dstE"));

        jTextField_W_Stat.setText(Json.get("W_stat"));
        jTextField_W_Icode.setText(Json.get("W_icode"));
        jTextField_W_ValE.setText(Json.get("W_valE"));
        jTextField_W_ValM.setText(Json.get("W_valM"));
        jTextField_W_DstE.setText(Json.get("W_dstE"));
        jTextField_W_DstM.setText(Json.get("W_dstM"));

        jTextField_edx.setText(Json.get("%edx"));
        jTextField_ecx.setText(Json.get("%ecx"));
        jTextField_eax.setText(Json.get("%eax"));
        jTextField_ebx.setText(Json.get("%ebx"));
        jTextField_esp.setText(Json.get("%esp"));
        jTextField_ebp.setText(Json.get("%ebp"));
        jTextField_esi.setText(Json.get("%esi"));
        jTextField_edi.setText(Json.get("%edi"));

        jTextField_D_Instr.setText(Json.get("D_code"));
        jTextField_E_Instr.setText(Json.get("E_code"));
        jTextField_M_Instr.setText(Json.get("M_code"));
        jTextField_W_Instr.setText(Json.get("W_code"));

        jTextField_Cycle.setText(Json.get("Cycle"));

    }

    private void getCode() {
        PipelineClient.Send(Request.getReqStr(Request.CODE, ""));
        String Code = PipelineClient.Receive();
        Code = Code.substring(1, Code.length() - 1);
        String[] rows = Code.split("#");
        Object[][] codes = new Object[rows.length][3];
        int i = 0, j = 1;
        int add = 0;
        for (String x : rows) {
            String temp = x.substring(1, x.length() - 1);
            String[] y = temp.split(":");
            codes[i][1] = y[0];
            codes[i][2] = y[1];
            codes[i][0] = Hex2String((String) Integer.toHexString(add));
            add += y[0].length() / 2;
            i++;
        }
        DefaultTableModel tableModel = (DefaultTableModel) jTable_Code.getModel();
        tableModel.setDataVector(codes, new String[]{"Address", "Binary Code", "Instruction"});
    }

    private void getMemory() {
        PipelineClient.Send(Request.getReqStr(Request.MEMORY, ""));
        memory = PipelineClient.ReceiveBytes(MEMORY_SIZE);
        int rows = memory.length / 4;
        Object[][] memoryDisplay = new Object[rows][2];
        int add = 0, i = 0;
        while (i < rows) {
            memoryDisplay[i][1] = Convert.ByteArray2String(add, 4);
            memoryDisplay[i][0] = Hex2String((String) Integer.toHexString(add));
            add += 4;
            i++;
        }
        DefaultTableModel tableModel = (DefaultTableModel) jTable_Memory.getModel();
        tableModel.setDataVector(memoryDisplay, new String[]{"Address", "Data"});
    }

    private void jButton_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PlayActionPerformed
        // TODO add your handling code here:
        setButtonVisable(false);
        int F = 1;
        if (jRadioButton_5HZ.isSelected()) {
            F = 5;
        }
        if (jRadioButton_20HZ.isSelected()) {
            F = 20;
        }
        PipelineClient.Send(Request.getReqStr(Request.PLAY, Integer.toString(F)));
        task = new ClientStep();
        timer.schedule(task, 0, 1000 / F);
    }//GEN-LAST:event_jButton_PlayActionPerformed

    private void jButton_NextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextStepActionPerformed
        // TODO add your handling code here:
        PipelineClient.Send(Request.getReqStr(Request.NEXT, ""));
        Display();
    }//GEN-LAST:event_jButton_NextStepActionPerformed

    private void jButton_StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StopActionPerformed
        // TODO add your handling code here:
        if (task != null) {
            task.cancel();
        }
        PipelineClient.Send(Request.getReqStr(Request.STOP, jTextField_Cycle.getText()));
        setButtonVisable(true);
        PipelineClient.clearInputStream();//****Thread?
    }//GEN-LAST:event_jButton_StopActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        // TODO add your handling code here:
        PipelineClient.Send(Request.getReqStr(Request.RESET, ""));
        Display();
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshActionPerformed
        // TODO add your handling code here:
        PipelineClient.Send(Request.getReqStr(Request.REFRESH, ""));
        Display();
        getCode();
        getMemory();
    }//GEN-LAST:event_jButton_RefreshActionPerformed

    private void jTabbedPane_NavigationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane_NavigationMouseClicked
        // TODO add your handling code here:
        getMemory();
    }//GEN-LAST:event_jTabbedPane_NavigationMouseClicked

    private void jButton_OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OpenFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            int count = 0;
            byte[] re;
            try {
                FileInputStream in = new FileInputStream(file);
                re = new byte[MAX_CODELEN];
                count = in.read(re);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "导入失败！\n" + e.getMessage(), "提示信息", JOptionPane.WARNING_MESSAGE);
                return;
            }
            PipelineClient.Send(Request.getReqStr(Request.OPENFILE, Integer.toString(count)));
            PipelineClient.SendBytes(re, count);
            getCode();
        }
    }//GEN-LAST:event_jButton_OpenFileActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Option;
    private javax.swing.JButton jButton_NextStep;
    private javax.swing.JButton jButton_OpenFile;
    private javax.swing.JButton jButton_Play;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JButton jButton_Stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Cycle;
    private javax.swing.JLabel jLabel_D_Icode;
    private javax.swing.JLabel jLabel_D_Ifun;
    private javax.swing.JLabel jLabel_D_Instr;
    private javax.swing.JLabel jLabel_D_RA;
    private javax.swing.JLabel jLabel_D_RB;
    private javax.swing.JLabel jLabel_D_Stat;
    private javax.swing.JLabel jLabel_D_ValC;
    private javax.swing.JLabel jLabel_D_ValP;
    private javax.swing.JLabel jLabel_Decode;
    private javax.swing.JLabel jLabel_E_DstE;
    private javax.swing.JLabel jLabel_E_DstM;
    private javax.swing.JLabel jLabel_E_Icode;
    private javax.swing.JLabel jLabel_E_Ifun;
    private javax.swing.JLabel jLabel_E_Instr;
    private javax.swing.JLabel jLabel_E_SrcA;
    private javax.swing.JLabel jLabel_E_SrcB;
    private javax.swing.JLabel jLabel_E_Stat;
    private javax.swing.JLabel jLabel_E_ValA;
    private javax.swing.JLabel jLabel_E_ValB;
    private javax.swing.JLabel jLabel_E_ValC;
    private javax.swing.JLabel jLabel_Excute;
    private javax.swing.JLabel jLabel_F_PredPC;
    private javax.swing.JLabel jLabel_Fetch;
    private javax.swing.JLabel jLabel_Instruction;
    private javax.swing.JLabel jLabel_M_CC;
    private javax.swing.JLabel jLabel_M_Cnd;
    private javax.swing.JLabel jLabel_M_DstE;
    private javax.swing.JLabel jLabel_M_DstM;
    private javax.swing.JLabel jLabel_M_Icode;
    private javax.swing.JLabel jLabel_M_Instr;
    private javax.swing.JLabel jLabel_M_Stat;
    private javax.swing.JLabel jLabel_M_ValA;
    private javax.swing.JLabel jLabel_M_ValE;
    private javax.swing.JLabel jLabel_Memory;
    private javax.swing.JLabel jLabel_Pipeline;
    private javax.swing.JLabel jLabel_Register;
    private javax.swing.JLabel jLabel_W_DstE;
    private javax.swing.JLabel jLabel_W_DstM;
    private javax.swing.JLabel jLabel_W_Icode;
    private javax.swing.JLabel jLabel_W_Instr;
    private javax.swing.JLabel jLabel_W_Stat;
    private javax.swing.JLabel jLabel_W_ValE;
    private javax.swing.JLabel jLabel_W_ValM;
    private javax.swing.JLabel jLabel_Writeback;
    private javax.swing.JLabel jLabel_eax;
    private javax.swing.JLabel jLabel_ebp;
    private javax.swing.JLabel jLabel_ebx;
    private javax.swing.JLabel jLabel_ecx;
    private javax.swing.JLabel jLabel_edi;
    private javax.swing.JLabel jLabel_edx;
    private javax.swing.JLabel jLabel_esi;
    private javax.swing.JLabel jLabel_esp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_About;
    private javax.swing.JPanel jPanel_Code;
    private javax.swing.JPanel jPanel_FIle;
    private javax.swing.JPanel jPanel_Memory;
    private javax.swing.JPanel jPanel_Process;
    private javax.swing.JRadioButton jRadioButton_1HZ;
    private javax.swing.JRadioButton jRadioButton_20HZ;
    private javax.swing.JRadioButton jRadioButton_5HZ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane_Navigation;
    private javax.swing.JTable jTable_Code;
    private javax.swing.JTable jTable_Memory;
    private javax.swing.JTextField jTextField_Cycle;
    private javax.swing.JTextField jTextField_D_Icode;
    private javax.swing.JTextField jTextField_D_Ifun;
    private javax.swing.JTextField jTextField_D_Instr;
    private javax.swing.JTextField jTextField_D_RA;
    private javax.swing.JTextField jTextField_D_RB;
    private javax.swing.JTextField jTextField_D_Stat;
    private javax.swing.JTextField jTextField_D_ValC;
    private javax.swing.JTextField jTextField_D_ValP;
    private javax.swing.JTextField jTextField_E_DstE;
    private javax.swing.JTextField jTextField_E_DstM;
    private javax.swing.JTextField jTextField_E_Icode;
    private javax.swing.JTextField jTextField_E_Ifun;
    private javax.swing.JTextField jTextField_E_Instr;
    private javax.swing.JTextField jTextField_E_SrcA;
    private javax.swing.JTextField jTextField_E_SrcB;
    private javax.swing.JTextField jTextField_E_Stat;
    private javax.swing.JTextField jTextField_E_ValA;
    private javax.swing.JTextField jTextField_E_ValB;
    private javax.swing.JTextField jTextField_E_ValC;
    private javax.swing.JTextField jTextField_F_PredPC;
    private javax.swing.JTextField jTextField_M_CC;
    private javax.swing.JTextField jTextField_M_Cnd;
    private javax.swing.JTextField jTextField_M_DstE;
    private javax.swing.JTextField jTextField_M_DstM;
    private javax.swing.JTextField jTextField_M_Icode;
    private javax.swing.JTextField jTextField_M_Instr;
    private javax.swing.JTextField jTextField_M_Stat;
    private javax.swing.JTextField jTextField_M_ValA;
    private javax.swing.JTextField jTextField_M_ValE;
    private javax.swing.JTextField jTextField_W_DstE;
    private javax.swing.JTextField jTextField_W_DstM;
    private javax.swing.JTextField jTextField_W_Icode;
    private javax.swing.JTextField jTextField_W_Instr;
    private javax.swing.JTextField jTextField_W_Stat;
    private javax.swing.JTextField jTextField_W_ValE;
    private javax.swing.JTextField jTextField_W_ValM;
    private javax.swing.JTextField jTextField_eax;
    private javax.swing.JTextField jTextField_ebp;
    private javax.swing.JTextField jTextField_ebx;
    private javax.swing.JTextField jTextField_ecx;
    private javax.swing.JTextField jTextField_edi;
    private javax.swing.JTextField jTextField_edx;
    private javax.swing.JTextField jTextField_esi;
    private javax.swing.JTextField jTextField_esp;
    // End of variables declaration//GEN-END:variables
}
